#configuracion de acceso a BD
#spring:
  #jpa:
   # database: mysql
   # show-sql: true
   # generate-ddl: true
   # hibernate:
    # ddl-auto: update
      
#estrategia de generacion de base de datos
  #datasource:
   # driverClassName: com.mysql.jdbc.Driver
   # url: jdbc:mysql://localhost/dbagencia?useSSL=false 
   # username: root
   # password: admin


#configuracion de acceso a BD
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop 
  #estrategia de generacion de base de datos
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/db_incaways
    username: postgres
    password: admin
   
server:
  port: 8090 